apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-pod-topology
spec:
  rules:
  - name: add-default-pod-topology-to-deployments 
    match:
      resources:
        kinds:
        - Deployment
    mutate:
      patchStrategicMerge:
        spec:
          template:
            metadata:
              labels:
                topologyKey: "{{request.object.metadata.name}}"
            spec:
              topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    topologyKey: "{{request.object.metadata.name}}"
